// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"kathub/internal/controllers"
	"kathub/internal/database"
	"kathub/internal/initialize"
	"kathub/internal/repository"
	"kathub/internal/services"
)

// Injectors from account.go:

func InitAccountRouterHandler() *controllers.AccountController {
	db := database.DatabaseConnection()
	accountRepository := repository.NewAccountRepositoryImpl(db)
	accountService := services.NewAccountServiceImpl(accountRepository)
	accountController := controllers.NewAccountController(accountService)
	return accountController
}

// Injectors from post.go:

func InitPostRouterHandler() *controllers.PostController {
	db := database.DatabaseConnection()
	postRepository := repository.NewPostRepositoryImpl(db)
	postService := services.NewPostServiceImpl(postRepository)
	postController := controllers.NewPostController(postService)
	return postController
}

// Injectors from user.go:

func InitUserRouterHandler() *controllers.UserController {
	db := database.DatabaseConnection()
	userRepository := repository.NewUsersRepositoryImpl(db)
	client := initialize.CreateSession()
	storageService := services.NewStorageServiceImpl(client)
	userService := services.NewUsersServiceImpl(userRepository, storageService)
	userController := controllers.NewUserController(userService)
	return userController
}
