basePath: /api
host: localhost:8080
info:
  contact: {}
  description: A Tag service API in Go using Gin framework
  title: Kathub API
  version: "1.0"
paths:
  /users:
    get:
      responses: {}
    post:
      responses: {}
swagger: "2.0"
